Source/MR/Controllers/TourPlanController.cs
using DataTables.Mvc;
using MR.Common;
using MR.Common.Paging;
using MR.Entities.Contract;
using MR.Entities.V1;
using MR.Services.Contract;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace MR.Controllers
{
    public class TourPlanController : Controller
    {

        #region Fields
        private readonly AbstractTourPlanServices abstractTourPlanServices;
        private readonly AbstractTourPlanMonthServices abstractTourPlanMonthServices;
        private readonly AbstractMasterWorkAtServices abstractMasterWorkAtServices;
        private readonly AbstractWorkTypeServices abstractWorkTypeServices;
        private readonly AbstractDoctorService abstractDoctorService;
        private readonly AbstractChemistService abstractChemistService;
        private readonly AbstractDoctorAndChemistServices abstractDoctorAndChemistService;
        private readonly AbstractRouteService _RouteServices;
        private readonly AbstractEmployeeService _AbstractEmployeeService;

        #endregion

        #region Ctor
        public TourPlanController(
            AbstractTourPlanServices abstractTourPlanServices,
            AbstractTourPlanMonthServices abstractTourPlanMonthServices,
            AbstractMasterWorkAtServices abstractMasterWorkAtServices,
            AbstractWorkTypeServices abstractWorkTypeServices,
            AbstractDoctorService abstractDoctorService,
            AbstractChemistService abstractChemistService,
            AbstractDoctorAndChemistServices abstractDoctorAndChemistService,
            AbstractRouteService routeServices,
            AbstractEmployeeService abstractEmployeeService
            )
        {
            this.abstractTourPlanServices = abstractTourPlanServices;
            this.abstractTourPlanMonthServices = abstractTourPlanMonthServices;
            this.abstractMasterWorkAtServices = abstractMasterWorkAtServices;
            this.abstractWorkTypeServices = abstractWorkTypeServices;
            this.abstractDoctorService = abstractDoctorService;
            this.abstractChemistService = abstractChemistService;
            this.abstractDoctorAndChemistService = abstractDoctorAndChemistService;
            this._RouteServices = routeServices;
            this._AbstractEmployeeService = abstractEmployeeService;
        }
        #endregion


        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CreateTourPlan(string TourPlanId = "MA==", int IsSubmitted = 1)
        {
            ViewBag.TourPlansId = ConvertTo.Integer(ConvertTo.Base64Decode(TourPlanId));
            ViewBag.IsSubmitted = IsSubmitted;
            return View();
        }
        public ActionResult CreateTourplanSingle(string TourPlanId = "MA==")
        {
            ViewBag.TourPlanDayId = ConvertTo.Integer(ConvertTo.Base64Decode(TourPlanId));
            ViewBag.WorkAtName = BindWorkAtDrp();
            ViewBag.WorkTypeName = BindWorkTypeDrp();
            ViewBag.RouteName = BindRouteDrp();
            ViewBag.EmployeeeDD = BindEmployeeDrp();
            ViewBag.EmployeeeId = ProjectSession.AdminUserID;

            return View();
        }

        private List<SelectListItem> BindEmployeeDrp()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            try
            {
                PageParam pageParam = new PageParam();
                pageParam.Offset = 0;
                pageParam.Limit = 0;

                var result = _AbstractEmployeeService.Employee_ReportingPerson(pageParam, "", ProjectSession.AdminRoleID, true);

                foreach (var employee in result.Values)
                {
                    items.Add(new SelectListItem() { Text = employee.FirstName.ToString(), Value = employee.Id.ToString() });
                }

                return items;
            }
            catch (Exception)
            {
                return items;
            }
        }

        public IList<SelectListItem> BindWorkAtDrp()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            try
            {
                PageParam pageParam = new PageParam();
                pageParam.Offset = 0;
                pageParam.Limit = 0;


                var models = _RouteServices.SelectAllRouteType(pageParam, "");

                foreach (var master in models.Values)
                {
                    items.Add(new SelectListItem() { Text = master.Name.ToString(), Value = Convert.ToString(master.Id) });
                }
                return items;
            }
            catch (Exception)
            {
                return items;
            }
        }

        public IList<SelectListItem> BindWorkTypeDrp()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            try
            {
                PageParam pageParam = new PageParam();
                pageParam.Offset = 0;
                pageParam.Limit = 0;


                var models = abstractWorkTypeServices.WorkType_All(pageParam, "");

                foreach (var master in models.Values)
                {
                    items.Add(new SelectListItem() { Text = master.Name.ToString(), Value = Convert.ToString(master.Id) });
                }
                return items;
            }
            catch (Exception)
            {
                return items;
            }
        }

        public IList<SelectListItem> BindRouteDrp()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            try
            {
                PageParam pageParam = new PageParam();
                pageParam.Offset = 0;
                pageParam.Limit = 0;


                var models = _RouteServices.SelectAll(pageParam, "");

                foreach (var master in models.Values)
                {
                    items.Add(new SelectListItem() { Text = master.Name.ToString(), Value = Convert.ToString(master.Id) });
                }
                return items;
            }
            catch (Exception)
            {
                return items;
            }
        }


        //Tour Plan Grid =======================================
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult TourPlanData([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel)
        {
            {
                int totalRecord = 0;
                int filteredRecord = 0;

                PageParam pageParam = new PageParam();
                pageParam.Offset = requestModel.Start;
                pageParam.Limit = requestModel.Length;

                string search = Convert.ToString(requestModel.Search.Value);
                var response = abstractTourPlanServices.TourPlan_All(pageParam, search);

                totalRecord = (int)response.TotalRecords;
                filteredRecord = (int)response.TotalRecords;

                return Json(new DataTablesResponse(requestModel.Draw, response.Values, filteredRecord, totalRecord), JsonRequestBehavior.AllowGet);
            }
        }

        //Tour Plan Month Grid =======================================
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult TourPlanMonthData([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel, int TourPlanId = 0)
        {
            {
                int totalRecord = 0;
                int filteredRecord = 0;

                PageParam pageParam = new PageParam();
                pageParam.Offset = requestModel.Start;
                pageParam.Limit = requestModel.Length;

                string search = Convert.ToString(requestModel.Search.Value);
                var response = abstractTourPlanMonthServices.TourPlanMonth_All(pageParam, search, TourPlanId);

                totalRecord = (int)response.TotalRecords;
                filteredRecord = (int)response.TotalRecords;

                return Json(new DataTablesResponse(requestModel.Draw, response.Values, filteredRecord, totalRecord), JsonRequestBehavior.AllowGet);
            }
        }

        //Dr call Grid =======================================
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public JsonResult DrCallList([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel, int TourPlanMonthId = 0)
        {
            {
                int totalRecord = 0;
                int filteredRecord = 0;

                PageParam pageParam = new PageParam();
                pageParam.Offset = requestModel.Start;
                pageParam.Limit = requestModel.Length;

                string search = Convert.ToString(requestModel.Search.Value);
                var response = abstractDoctorService.SelectAll(pageParam, search, TourPlanMonthId);

                totalRecord = (int)response.TotalRecords;
                filteredRecord = (int)response.TotalRecords;

                return Json(new DataTablesResponse(requestModel.Draw, response.Values, filteredRecord, totalRecord), JsonRequestBehavior.AllowGet);
            }
        }

        //Chemist call Grid =======================================
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public JsonResult ChemistCallList([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel, int TourPlanMonthId = 0)

        {
            {
                int totalRecord = 0;
                int filteredRecord = 0;

                PageParam pageParam = new PageParam();
                pageParam.Offset = requestModel.Start;
                pageParam.Limit = requestModel.Length;

                string search = Convert.ToString(requestModel.Search.Value);
                var response = abstractChemistService.SelectAll(pageParam, search, TourPlanMonthId);

                totalRecord = (int)response.TotalRecords;
                filteredRecord = (int)response.TotalRecords;

Source/MR/Views/TourPlan/Index.cshtml
@using MR.Pages;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.AntiForgeryToken()
<link href="https://cdn.rawgit.com/t4t5/sweetalert/v0.2.0/lib/sweet-alert.css" rel="stylesheet" />
<style>
    .showSweetAlert h2 {
        font-size: 17px;
    }
</style>

<!-- Page Title -->
<div class="page-breadcrumb">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="d-flex flex-column flex-sm-row align-items-sm-center">
                    <h6 class="mb-0 pb-3 pb-sm-0 order-2 order-sm-1 mr-auto">Tourplan Manager</h6>
                    <nav aria-label="breadcrumb" class="order-1 order-sm-2 ml-sm-3">
                        <ol class="breadcrumb mb-0 pl-0">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Home</a></li>

                            <li class="breadcrumb-item active" aria-current="page">Tourplan Manager</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="page-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="alert alert-warning alert-dismissible fw-semibold fade show" role="alert">
                    Hey! Your last date of july month tour plan submit is 30/07/2021
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
            <div class="col-12 mb-3">
                <a href="@Url.Action("CreateTourPlan","TourPlan")?IsSubmitted=0" class="btn btn-primary" role="button"><i data-eva="plus-outline" class="hw-16 fill-white mr-1"></i>Create Tourplan</a>
            </div>

            <div class="col-12">
                <div class="card table-responsive">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table border rounded display nowrap" id="TourPlanList"></table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




<!-- Navbar Backdrop -->
<div class="navbar-backdrop"></div>


<!-- Scripts -->
<!-- Custom JS -->

<script src="https://cdn.rawgit.com/t4t5/sweetalert/v0.2.0/lib/sweet-alert.min.js"></script>


<!-- Scripts -->
<script src="~/assets/vendors/jquery/dist/jquery.min.js"></script>
<script src="~/assets/vendors/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/assets/vendors/eva-icons/eva.min.js"></script>
<script src="~/assets/vendors/simplebar/dist/simplebar.min.js"></script>
<script src="~/assets/vendors/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
<script src="https://cdn.datatables.net/v/bs4/dt-1.10.24/fc-3.3.2/r-2.2.7/datatables.min.js"></script>
<script src="~/assets/vendors/daterangepicker/moment.min.js"></script>
<script src="~/assets/vendors/daterangepicker/daterangepicker.js"></script>
<script src="~/assets/vendors/summernote/dist/summernote.min.js"></script>
<script src="~/assets/vendors/slick-carousel/slick/slick.min.js"></script>
<script src="~/assets/vendors/jquery.repeater/jquery.repeater.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
<!-- Custom JS -->
<script src="~/assets/js/main.min.js"></script>


<script>

     jQuery(document).ready(function () {
        TableDatatablesColreorder.init();
    });

    var TableDatatablesColreorder = function () {
    var initTable1 = function () {
        var table = $('#TourPlanList');

        var oTable = table.dataTable({
            "stateSave": true,
            "autoWidth": false,
            "paging": true,
            // Internationalisation. For more info refer to http://datatables.net/manual/i18n
            "language": {
                "aria": {
                    "sortAscending": ": activate to sort column ascending",
                    "sortDescending": ": activate to sort column descending"
                },
                "emptyTable": "No data available in table",
                "info": "Showing _START_ to _END_ of _TOTAL_ entries",
                "infoEmpty": "No entries found",
                "infoFiltered": "(filtered1 from _MAX_ total entries)",
                "lengthMenu": "_MENU_ entries",
                "search": "Search:",
                "zeroRecords": "No matching records found"
            },
            "pageLength": 10,
            "processing": true,
            "serverSide": true,
            "ajax": {
                async: true,
                url: '@Url.Action(Actions.TourPlanData, Controllers.TourPlan, new { area =""})',
                type: "post",
                data: BuildSearchCriteria()
            },
            "columns": [
                { "title": "#", "data": "Id", "orderable": true },
                { "title": "Month", "data": "Month", "orderable": true },
                { "title": "SubmittedDate", "data": "SubmittedDate", "orderable": true },
                { "title": "LastDate", "data": "LastDate", "orderable": true },
                {
                    "title": "Status", "data": "IsSubmitted",
                    "render": function (data, type, row) {
                        var appendstring = '';
                        if (data) {
                            appendstring += "<div class='badge badge-success p-2'>Submitted</div>";
                        }
                        else {
                            appendstring += "<div class='badge badge-light border p-2'>Draft</div>";
                        }
                        return appendstring;
                    },
                    "orderable": false
                },
                {
                    "title": "Actions", "data": "IsSubmitted",
                    "render": function (data, type, row) {
                        var appendstring = '';
                        if (data) {
                            appendstring += `<a href='@Url.Action("CreateTourPlan","TourPlan")?TourPlanId=${btoa(row["Id"])}&IsSubmitted=1' class='btn btn-primary'>View tour plan</a>`;
                        }
                        else {
                            appendstring += `<a href='@Url.Action("CreateTourPlan","TourPlan")?TourPlanId=${btoa(row["Id"])}&IsSubmitted=0' class='btn btn-soft-primary border'>Edit tour plan</a>`;
                        }
                        return appendstring;
                    },
                    "orderable": false
                },

            ],
            "buttons": [
                {

                },

                //{ extend: 'pdf', className: 'btn green btn-outline' },
                //{ extend: 'excel', className: 'btn yellow btn-outline ' },
            ],

            // setup responsive extension: http://datatables.net/extensions/responsive/
            responsive: true,

            "lengthMenu": [
                [5, 10, 15, 20],
                [5, 10, 15, 20]
            ],

            "dom": "<'row' <'col-md-12'B>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r><'table-scrollable't><'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>", // horizobtal scrollable datatable

            // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
            // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js).
            // So when dropdowns used the scrollable div should be removed.
            //"dom": "<'row' <'col-md-12'T>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r>t<'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>",
        });
    }

    return {

        //main function to initiate the module
        init: function () {
            if ($.fn.DataTable.isDataTable("#TourPlanList")) {
                $('#TourPlanList').dataTable().fnDestroy();
            }
            initTable1();
        }

    };

}();

    function BuildSearchCriteria() {
        try {
            var param = {};
            return addRequestVerificationToken(param);
        } catch (e) { }
    }

    function addRequestVerificationToken(data) {
        data.__RequestVerificationToken = $('input[name=__RequestVerificationToken]').val();
        return data;
    }


</script>